name: local_keep
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # For secure storage of password hash
  flutter_secure_storage: ^9.0.0
  # For encryption and decryption
  encrypt: ^5.0.3
  # For hashing with PBKDF2
  crypto: ^3.0.3
  # For local database storage
  sqflite: ^2.3.0
  path: ^1.8.3
  # For UI improvements
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true